import { TextField } from './EditorField.jsx';

const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const move = (list, index, direction) => { const target = index + direction; if (target < 0 || target >= list.length) return list; const next = [...list]; [next[index], next[target]] = [next[target], next[index]]; return next; };

export function EducationEditor({ items, onChange }) {
  const updateStage = (id, key, value) => onChange(items.map(item => item.id === id ? { ...item, [key]: value } : item));
  const updateExperiences = (id, experiences) => updateStage(id, 'experiences', experiences);
  return <div><button className="editor-add" onClick={() => onChange([...items, { id: uid(), school: 'New school', description: '', grade: '', startDate: '', endDate: 'Present', experiences: [] }])}>+ Add Education Stage</button>{items.map((stage, index) => <article className="editor-item" key={stage.id}><div className="editor-item-top"><strong>Stage {index + 1}</strong><span><button onClick={() => onChange(move(items, index, -1))} disabled={index === 0}>↑</button><button onClick={() => onChange(move(items, index, 1))} disabled={index === items.length - 1}>↓</button><button className="danger" onClick={() => { if (window.confirm('Delete this Education Stage and all of its Experiences?')) onChange(items.filter(item => item.id !== stage.id)); }}>Delete</button></span></div><TextField label="School Name" value={stage.school} onChange={value => updateStage(stage.id, 'school', value)} /><TextField label="Description" value={stage.description} multiline onChange={value => updateStage(stage.id, 'description', value)} /><TextField label="Grade" value={stage.grade} onChange={value => updateStage(stage.id, 'grade', value)} /><TextField label="Start Date" value={stage.startDate} onChange={value => updateStage(stage.id, 'startDate', value)} /><TextField label="End Date / Present" value={stage.endDate} onChange={value => updateStage(stage.id, 'endDate', value)} /><button className="editor-add secondary-add" onClick={() => updateExperiences(stage.id, [...stage.experiences, { id: uid(), text: 'New experience' }])}>+ Add Experience</button>{stage.experiences.map((entry, entryIndex) => <div className="nested-editor-row" key={entry.id}><input value={entry.text} aria-label={`Experience ${entryIndex + 1}`} onChange={event => updateExperiences(stage.id, stage.experiences.map(item => item.id === entry.id ? { ...item, text: event.target.value } : item))} /><button onClick={() => updateExperiences(stage.id, move(stage.experiences, entryIndex, -1))} disabled={entryIndex === 0}>↑</button><button onClick={() => updateExperiences(stage.id, move(stage.experiences, entryIndex, 1))} disabled={entryIndex === stage.experiences.length - 1}>↓</button><button className="danger" onClick={() => updateExperiences(stage.id, stage.experiences.filter(item => item.id !== entry.id))}>×</button></div>)}</article>)}</div>;
}

export function SkillsEditor({ groups, onChange }) {
  const updateGroup = (id, key, value) => onChange(groups.map(group => group.id === id ? { ...group, [key]: value } : group));
  const deleteGroup = (group, moveSkills) => { const target = groups.find(item => item.id !== group.id); if (moveSkills && target) onChange(groups.filter(item => item.id !== group.id).map(item => item.id === target.id ? { ...item, skills: [...item.skills, ...group.skills] } : item)); else if (window.confirm(`Delete ${group.name} and all ${group.skills.length} Skills?`)) onChange(groups.filter(item => item.id !== group.id)); };
  return <div><button className="editor-add" onClick={() => onChange([...groups, { id: uid(), name: 'New Skill Group', skills: [] }])}>+ Add Skill Group</button>{groups.map((group, index) => <article className="editor-item" key={group.id}><div className="editor-item-top"><strong>Group {index + 1}</strong><span><button onClick={() => onChange(move(groups, index, -1))} disabled={index === 0}>↑</button><button onClick={() => onChange(move(groups, index, 1))} disabled={index === groups.length - 1}>↓</button>{group.skills.length > 0 && groups.length > 1 && <button onClick={() => { if (window.confirm('Move every Skill to another Group, then delete this Group?')) deleteGroup(group, true); }}>Move & delete</button>}<button className="danger" onClick={() => deleteGroup(group, false)}>Delete group{group.skills.length ? ' & skills' : ''}</button></span></div><TextField label="Skill Group Name" value={group.name} onChange={value => updateGroup(group.id, 'name', value)} /><button className="editor-add secondary-add" onClick={() => updateGroup(group.id, 'skills', [...group.skills, { id: uid(), name: 'New skill' }])}>+ Add Skill</button>{group.skills.map((skill, skillIndex) => <div className="nested-editor-row skill-editor-row" key={skill.id}><input value={skill.name} aria-label={`Skill ${skillIndex + 1}`} onChange={event => updateGroup(group.id, 'skills', group.skills.map(item => item.id === skill.id ? { ...item, name: event.target.value } : item))} /><button onClick={() => updateGroup(group.id, 'skills', move(group.skills, skillIndex, -1))} disabled={skillIndex === 0}>←</button><button onClick={() => updateGroup(group.id, 'skills', move(group.skills, skillIndex, 1))} disabled={skillIndex === group.skills.length - 1}>→</button>{groups.length > 1 && <select aria-label={`Move ${skill.name} to another group`} value="" onChange={event => { const targetId = event.target.value; if (!targetId) return; onChange(groups.map(item => item.id === group.id ? { ...item, skills: item.skills.filter(entry => entry.id !== skill.id) } : item.id === targetId ? { ...item, skills: [...item.skills, skill] } : item)); }}><option value="">Move to…</option>{groups.filter(item => item.id !== group.id).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}<button className="danger" onClick={() => updateGroup(group.id, 'skills', group.skills.filter(item => item.id !== skill.id))}>×</button></div>)}</article>)}</div>;
}
