import { usePortfolio } from '../context/PortfolioContext.jsx';
import EditableText from '../editor/EditableText.jsx';

export default function CollectionCard({ item, type, onOpen, detailLabel, galleryLabel, achievementLabel }) {
  const { content, update, hostMode, requestEditor } = usePortfolio();
  const collectionKey = type === 'competition' ? 'competitions' : 'projects';
  const labels = type === 'competition' ? item.tags || [] : item.technologies || [];
  const updateItem = (key, value) => update(current => ({ ...current, [collectionKey]: current[collectionKey].map(entry => entry.id === item.id ? { ...entry, [key]: value } : entry) }));
  const edit = () => requestEditor({ kind: type, id: item.id, panel: 'details' });
  const editGallery = () => requestEditor({ kind: type, id: item.id, panel: 'gallery' });
  const itemIndex = content[collectionKey].findIndex(entry => entry.id === item.id);
  const move = direction => update(current => { const items = [...current[collectionKey]]; const target = itemIndex + direction; if (target < 0 || target >= items.length) return current; [items[itemIndex], items[target]] = [items[target], items[itemIndex]]; return { ...current, [collectionKey]: items }; });
  const remove = () => { if (window.confirm(`Delete ${item.title}?`)) update(current => ({ ...current, [collectionKey]: current[collectionKey].filter(entry => entry.id !== item.id) })); };
  const primaryAction = hostMode ? edit : () => onOpen('cover');
  const visibleGalleryCount = (item.gallery || []).filter(image => typeof image === 'string' || !image.hidden).length;
  return <article id={`${type}-${item.id}`} className={`collection-card ${hostMode ? 'is-host-editable' : ''}`}>
    <button className="collection-cover" onClick={primaryAction} aria-label={hostMode ? `Edit ${item.title}` : `Open ${item.title}`}>{item.coverImage ? <img src={item.coverImage} alt="" loading="lazy" style={{ objectPosition: item.coverPosition || '50% 50%' }} /> : <div className="collection-cover-empty">No highlight image</div>}<span>{hostMode ? 'Edit' : <EditableText value={item.date} onChange={value => updateItem('date', value)} />}</span></button>
    <div className="collection-info"><p className="project-category"><EditableText value={item.label} onChange={value => updateItem('label', value)} /></p><h3><EditableText value={item.title} onChange={value => updateItem('title', value)} /></h3><p className="collection-description"><EditableText value={item.description} multiline onChange={value => updateItem('description', value)} /></p>{type === 'competition' && <p className="achievement"><b>{achievementLabel}</b><span><EditableText value={item.achievement || ''} onChange={value => updateItem('achievement', value)} /></span></p>}<div className="collection-meta">{hostMode ? <button className="gallery-link" onClick={editGallery}>Edit Gallery</button> : <button className="gallery-link" onClick={() => onOpen('gallery')}>{galleryLabel} {visibleGalleryCount ? `(${visibleGalleryCount})` : ''} ↗</button>}<div className="collection-tags">{labels.map((label, index) => <EditableText key={`${label}-${index}`} value={label} onChange={value => updateItem(type === 'competition' ? 'tags' : 'technologies', labels.map((entry, labelIndex) => labelIndex === index ? value : entry))} />)}</div></div>{hostMode ? <><button className="card-open host-card-edit" onClick={edit}>Edit {type} details ↗</button><div className="host-card-actions"><button onClick={() => move(-1)} disabled={itemIndex === 0}>Move up</button><button onClick={() => move(1)} disabled={itemIndex === content[collectionKey].length - 1}>Move down</button><button className="danger" onClick={remove}>Delete</button></div></> : <div className="collection-links">{type === 'project' && item.github && <a href={item.github} target="_blank" rel="noreferrer">GitHub ↗</a>}{type === 'project' && item.liveDemo && <a href={item.liveDemo} target="_blank" rel="noreferrer">Demo ↗</a>}{item.galleryUrl && <a href={item.galleryUrl} target="_blank" rel="noreferrer">External gallery ↗</a>}<button className="card-open" onClick={() => onOpen('cover')}>{detailLabel} ↗</button></div>}</div>
  </article>;
}
