import EditableText from '../editor/EditableText.jsx';
import { usePortfolio } from '../context/PortfolioContext.jsx';

export default function EducationSkills() {
  const { content, update } = usePortfolio();
  const setAbout = (key, value) => update(current => ({ ...current, about: { ...current.about, [key]: value } }));
  const setStage = (id, key, value) => update(current => ({ ...current, educationStages: current.educationStages.map(stage => stage.id === id ? { ...stage, [key]: value } : stage) }));
  const setExperience = (stageId, experienceId, value) => update(current => ({ ...current, educationStages: current.educationStages.map(stage => stage.id === stageId ? { ...stage, experiences: stage.experiences.map(entry => entry.id === experienceId ? { ...entry, text: value } : entry) } : stage) }));
  const setGroup = (id, value) => update(current => ({ ...current, skillGroups: current.skillGroups.map(group => group.id === id ? { ...group, name: value } : group) }));
  const setSkill = (groupId, skillId, value) => update(current => ({ ...current, skillGroups: current.skillGroups.map(group => group.id === groupId ? { ...group, skills: group.skills.map(skill => skill.id === skillId ? { ...skill, name: value } : skill) } : group) }));
  return <div className="education-skills"><section className="education-column"><header><p className="kicker"><EditableText value={content.about.educationTitle} onChange={value => setAbout('educationTitle', value)} /></p><small><EditableText value={content.about.educationDirection} onChange={value => setAbout('educationDirection', value)} /></small></header><div className="education-timeline">{content.educationStages.map(stage => <article key={stage.id}><div className="education-date"><EditableText value={stage.startDate} onChange={value => setStage(stage.id, 'startDate', value)} /> — <EditableText value={stage.endDate} onChange={value => setStage(stage.id, 'endDate', value)} /></div><h3><EditableText value={stage.school} onChange={value => setStage(stage.id, 'school', value)} /></h3><p><EditableText value={stage.description} onChange={value => setStage(stage.id, 'description', value)} /></p>{stage.grade && <b><EditableText value={stage.grade} onChange={value => setStage(stage.id, 'grade', value)} /></b>}{stage.experiences.length > 0 && <ul>{stage.experiences.map(entry => <li key={entry.id}><EditableText value={entry.text} onChange={value => setExperience(stage.id, entry.id, value)} /></li>)}</ul>}</article>)}</div></section><section className="skills-column"><header><p className="kicker"><EditableText value={content.about.skillsTitle} onChange={value => setAbout('skillsTitle', value)} /></p></header><div className="skill-groups">{content.skillGroups.map(group => <article key={group.id}><h3><EditableText value={group.name} onChange={value => setGroup(group.id, value)} /></h3><div>{group.skills.map(skill => <span key={skill.id}><EditableText value={skill.name} onChange={value => setSkill(group.id, skill.id, value)} /></span>)}</div></article>)}</div></section></div>;
}
