import { useRef } from 'react';
import { usePortfolio } from '../context/PortfolioContext.jsx';
import EditableText from '../editor/EditableText.jsx';

const dataUrl = file => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); });

export default function Hero() {
  const { content, update, hostMode } = usePortfolio();
  const { hero, profile } = content;
  const upload = useRef(null);
  const setHero = (key, value) => update(current => ({ ...current, hero: { ...current.hero, [key]: value } }));
  const replacePortrait = async event => { const file = event.target.files?.[0]; if (!file || !file.type.startsWith('image/') || file.size > 1800000) return; setHero('portrait', await dataUrl(file)); };
  return <section className="hero hero-identity" id="home"><div className="hero-overlay" /><div className="hero-stars" aria-hidden="true" /><div className="hero-copy"><p className="hero-support"><EditableText value={hero.supportingLabel} onChange={value => setHero('supportingLabel', value)} /></p><h1><EditableText value={hero.fullName} onChange={value => setHero('fullName', value)} /></h1><div className="hero-credentials"><EditableText value={hero.role} onChange={value => setHero('role', value)} /><span>·</span><EditableText value={hero.university} onChange={value => setHero('university', value)} /></div><p className="hero-intro"><EditableText value={hero.intro} multiline onChange={value => setHero('intro', value)} /></p><div className="hero-focus">{hero.technicalFocus.map((item, index) => <EditableText key={`${item}-${index}`} value={item} onChange={value => setHero('technicalFocus', hero.technicalFocus.map((entry, itemIndex) => itemIndex === index ? value : entry))} />)}</div><div className="hero-actions"><a className="button" href={hero.primaryUrl}><EditableText value={hero.primaryLabel} onChange={value => setHero('primaryLabel', value)} /> <b>↗</b></a><a className="text-link" href={hero.secondaryUrl}><EditableText value={hero.secondaryLabel} onChange={value => setHero('secondaryLabel', value)} /> <b>↓</b></a></div></div><div className={`hero-portrait ${hostMode ? 'is-editable' : ''}`} style={{ '--portrait-position': hero.portraitPosition }}><img src={hero.portrait || profile.portrait} alt={`${hero.fullName} portrait`} />{hostMode && <div className="portrait-editor"><button onClick={() => upload.current?.click()}>Replace portrait</button><button onClick={() => setHero('portrait', '')}>Remove</button><label>Position<input value={hero.portraitPosition} onChange={event => setHero('portraitPosition', event.target.value)} placeholder="50% 50%" /></label><input ref={upload} type="file" accept="image/*" onChange={replacePortrait} hidden /></div>}</div></section>;
}
