import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase.js';
import { blankCompetition, blankLearning, blankProject } from '../data/portfolio.js';
import { usePortfolio } from '../context/PortfolioContext.jsx';
import CollectionEditor from '../editor/CollectionEditor.jsx';
import { ImageField, TextField } from '../editor/EditorField.jsx';
import StrengthEditor from '../editor/StrengthEditor.jsx';

const tabs = ['Content', 'Profile', 'About', 'Projects', 'Competitions', 'Learning', 'Strengths'];
const setAt = (object, key, value) => ({ ...object, [key]: value });
export default function HostAccess() {
  const { content, update, hostMode, setHostMode, editorRequest, requestEditor, save, cancel, reset, status, isDirty } = usePortfolio();
  const [open, setOpen] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [authNote, setAuthNote] = useState(''); const [tab, setTab] = useState('Content'); const [activeItem, setActiveItem] = useState(null);
  const setContent = (key, value) => update(current => setAt(current, key, value));
  const setNested = (group, key, value) => update(current => ({ ...current, [group]: setAt(current[group], key, value) }));
  const setAboutList = (key, index, field, value) => setNested('about', key, content.about[key].map((entry, entryIndex) => entryIndex === index ? setAt(entry, field, value) : entry));
  async function login(event) { event.preventDefault(); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) return setAuthNote('Login failed. Check your email and password.'); setHostMode(true); setOpen(false); setAuthNote(''); }
  function exit() { if (isDirty && !window.confirm('Discard unsaved changes and exit Host Mode?')) return; if (isDirty) cancel(); setHostMode(false); }
  const field = (group, key, label, multiline = false) => <TextField label={label} value={content[group][key]} multiline={multiline} onChange={value => setNested(group, key, value)} />;
  useEffect(() => {
    const activate = async () => { setOpen(true); const { data, error } = await supabase.auth.getSession(); if (error) setAuthNote('Unable to check your Host session. Please sign in again.'); else if (data.session) { setHostMode(true); setOpen(false); } };
    const handler = event => { if (event.ctrlKey && event.shiftKey && event.key.toLowerCase() === 'e') { event.preventDefault(); activate(); } };
    if (new URLSearchParams(window.location.search).get('host') === '1') activate();
    window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler);
  }, [setHostMode]);
  useEffect(() => { if (!editorRequest) return; const tabName = editorRequest.kind === 'competition' ? 'Competitions' : editorRequest.kind === 'project' ? 'Projects' : null; if (!tabName) return; setTab(tabName); setActiveItem(editorRequest); requestEditor(null); }, [editorRequest, requestEditor]);
  return <>
    {open && <div className="host-dialog"><div><form onSubmit={login}><button type="button" onClick={() => setOpen(false)}>×</button><p>PRIVATE HOST ACCESS</p><h2>Manage your portfolio.</h2><input type="email" placeholder="Email" required value={email} onChange={event => setEmail(event.target.value)} /><input type="password" placeholder="Password" required value={password} onChange={event => setPassword(event.target.value)} /><button>Unlock editor ↗</button><small>{authNote}</small></form></div></div>}
    {hostMode && <aside className="cms-drawer" aria-label="Portfolio editor"><header><div><p>HOST MODE</p><h2>Content studio</h2></div><button onClick={exit}>Exit ×</button></header><nav>{tabs.map(item => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav><div className="cms-scroll">
      {tab === 'Content' && <><h3>Navigation</h3>{content.navigation.map((item, index) => <TextField key={item.id} label={`Navigation ${index + 1}`} value={item.label} onChange={value => setContent('navigation', content.navigation.map((entry, itemIndex) => itemIndex === index ? setAt(entry, 'label', value) : entry))} />)}<h3>Homepage identity</h3>{[['fullName', 'Full name'], ['role', 'Role / degree'], ['university', 'University'], ['supportingLabel', 'Supporting label'], ['intro', 'Short introduction'], ['primaryLabel', 'Primary CTA label'], ['primaryUrl', 'Primary CTA URL'], ['secondaryLabel', 'Secondary CTA label'], ['secondaryUrl', 'Secondary CTA URL']].map(([key, label]) => <TextField key={key} label={label} type={key.includes('Url') ? 'url' : 'text'} value={content.hero[key]} multiline={key === 'intro'} onChange={value => setNested('hero', key, value)} />)}<TextField label="Technical focus (comma separated)" value={content.hero.technicalFocus.join(', ')} onChange={value => setNested('hero', 'technicalFocus', value.split(',').map(item => item.trim()).filter(Boolean))} /><h3>Section copy and calls to action</h3>{Object.entries(content.sections).flatMap(([sectionKey, values]) => Object.entries(values).map(([key, value]) => <TextField key={`${sectionKey}-${key}`} label={`${sectionKey} · ${key}`} value={value} onChange={next => setContent('sections', { ...content.sections, [sectionKey]: setAt(values, key, next) })} />))}</>}
      {tab === 'Profile' && <><h3>Personal content</h3>{[['name', 'Name'], ['initials', 'Initials'], ['role', 'Role'], ['location', 'Location'], ['email', 'Email'], ['education', 'Education'], ['resumeUrl', 'Resume URL'], ['portraitCaption', 'Photo caption']].map(([key, label]) => <TextField key={key} label={label} value={content.profile[key]} type={key.includes('Url') ? 'url' : key === 'email' ? 'email' : 'text'} onChange={value => setNested('profile', key, value)} />)}<TextField label="Languages (comma separated)" value={(content.profile.languages || []).join(', ')} onChange={value => setNested('profile', 'languages', value.split(',').map(item => item.trim()).filter(Boolean))} /><TextField label="Biography" value={content.profile.bio} multiline onChange={value => setNested('profile', 'bio', value)} /><ImageField label="Replace profile photo" value={content.profile.portrait} onChange={value => value && setNested('profile', 'portrait', value)} /><h3>Social links</h3>{content.contact.socialLinks.map((link, index) => <div key={link.id} className="link-fields"><TextField label="Label" value={link.label} onChange={value => setNested('contact', 'socialLinks', content.contact.socialLinks.map((entry, entryIndex) => entryIndex === index ? setAt(entry, 'label', value) : entry))} /><TextField label="URL" value={link.url} type="url" onChange={value => setNested('contact', 'socialLinks', content.contact.socialLinks.map((entry, entryIndex) => entryIndex === index ? setAt(entry, 'url', value) : entry))} /></div>)}</>}
      {tab === 'About' && <><h3>About copy</h3>{[['label', 'Section label'], ['kicker', 'Kicker'], ['title', 'Title'], ['emphasis', 'Title emphasis'], ['educationLabel', 'Education label'], ['contactLabel', 'Contact label'], ['experienceLabel', 'Experience label'], ['highlightsLabel', 'Highlights label']].map(([key, label]) => field('about', key, label))}<h3>Statistics</h3>{content.about.stats.map((item, index) => <div className="editor-item" key={item.id}>{['number', 'label', 'value'].map(key => <TextField key={key} label={key} value={item[key]} onChange={value => setAboutList('stats', index, key, value)} />)}</div>)}<h3>Experience</h3>{content.about.experience.map((item, index) => <div className="editor-item" key={item.id}>{['period', 'title', 'detail'].map(key => <TextField key={key} label={key} value={item[key]} multiline={key === 'detail'} onChange={value => setAboutList('experience', index, key, value)} />)}</div>)}<h3>Highlights</h3>{content.about.highlights.map((item, index) => <div className="editor-item" key={item.id}>{['label', 'value'].map(key => <TextField key={key} label={key} value={item[key]} onChange={value => setAboutList('highlights', index, key, value)} />)}</div>)}</>}
      {tab === 'Projects' && <CollectionEditor title="Project" kind="project" items={content.projects} create={blankProject} updateItems={items => setContent('projects', items)} activeId={activeItem?.kind === 'project' ? activeItem.id : null} onActiveChange={id => setActiveItem(id ? { kind: 'project', id } : null)} />}
      {tab === 'Competitions' && <CollectionEditor title="Competition" kind="competition" items={content.competitions} create={blankCompetition} updateItems={items => setContent('competitions', items)} activeId={activeItem?.kind === 'competition' ? activeItem.id : null} onActiveChange={id => setActiveItem(id ? { kind: 'competition', id } : null)} />}
      {tab === 'Learning' && <CollectionEditor title="Learning experience" kind="learning experience" items={content.learningJourney} create={blankLearning} updateItems={items => setContent('learningJourney', items)} activeId={activeItem?.kind === 'learning' ? activeItem.id : null} onActiveChange={id => setActiveItem(id ? { kind: 'learning', id } : null)} />}
      {tab === 'Strengths' && <><h3>Capability cards</h3><StrengthEditor items={content.strengths} updateItems={items => setContent('strengths', items)} /></>}
    </div><footer><small>{status || (isDirty ? 'Unsaved changes' : 'All changes saved')}</small><span><button onClick={cancel} disabled={!isDirty}>Cancel</button><button onClick={() => { if (window.confirm('Reset every portfolio item to defaults? Save afterwards to publish.')) reset(); }}>Reset</button><button className="save" onClick={save} disabled={!isDirty}>Save</button></span></footer></aside>}
  </>;
}
