import Reveal from './Reveal.jsx';
import EditableText from '../editor/EditableText.jsx';
import { usePortfolio } from '../context/PortfolioContext.jsx';

export default function LearningJourney() {
  const { content, update, hostMode, requestEditor } = usePortfolio();
  const copy = content.sections.learning;
  const entries = hostMode ? content.learningJourney : content.learningJourney.filter(item => !item.hidden);
  const setCopy = (key, value) => update(current => ({ ...current, sections: { ...current.sections, learning: { ...current.sections.learning, [key]: value } } }));
  const setItem = (id, key, value) => update(current => ({ ...current, learningJourney: current.learningJourney.map(item => item.id === id ? { ...item, [key]: value } : item) }));
  const setKnowledge = (itemId, knowledgeId, key, value) => update(current => ({ ...current, learningJourney: current.learningJourney.map(item => item.id === itemId ? { ...item, knowledge: (item.knowledge || []).map(entry => entry.id === knowledgeId ? { ...entry, [key]: value } : entry) } : item) }));
  return <section className="learning-section" id="learning"><div className="section"><div className="section-label"><EditableText value={copy.label} onChange={value => setCopy('label', value)} /></div><Reveal className="projects-heading"><h2><EditableText value={copy.title} onChange={value => setCopy('title', value)} /><br /><em><EditableText value={copy.emphasis} onChange={value => setCopy('emphasis', value)} /></em></h2><p><EditableText value={copy.description} multiline onChange={value => setCopy('description', value)} /></p></Reveal>{entries.length ? <div className="learning-categories">{entries.map(item => {
    const knowledge = hostMode ? (item.knowledge || []) : (item.knowledge || []).filter(entry => !entry.hidden);
    const legacyTags = [...(item.topics || []), ...(item.technologies || [])];
    return <Reveal key={item.id}><article className={`learning-category ${item.hidden ? 'is-hidden-host' : ''}`}><div className="learning-category-head"><div><p className="project-category"><EditableText value={item.category || ''} onChange={value => setItem(item.id, 'category', value)} /></p><h3><EditableText value={item.title} onChange={value => setItem(item.id, 'title', value)} /></h3></div><div className="learning-status"><span><EditableText value={item.status || ''} onChange={value => setItem(item.id, 'status', value)} /></span><small><EditableText value={item.period || ''} onChange={value => setItem(item.id, 'period', value)} /></small></div></div><p className="learning-summary"><EditableText value={item.summary || ''} multiline onChange={value => setItem(item.id, 'summary', value)} /></p>{legacyTags.length > 0 && <div className="learning-tags">{legacyTags.map((tag, index) => <span key={`${tag}-${index}`}>{tag}</span>)}</div>}{knowledge.length > 0 && <div className="knowledge-points">{knowledge.map(entry => <section className={entry.hidden ? 'is-hidden-host' : ''} key={entry.id}><div><h4><EditableText value={entry.title} onChange={value => setKnowledge(item.id, entry.id, 'title', value)} /></h4><span><EditableText value={entry.progress || ''} onChange={value => setKnowledge(item.id, entry.id, 'progress', value)} /></span></div>{entry.description && <p><EditableText value={entry.description} multiline onChange={value => setKnowledge(item.id, entry.id, 'description', value)} /></p>}<nav>{entry.resourceUrl && <a href={entry.resourceUrl} target="_blank" rel="noreferrer"><EditableText value={entry.resourceLabel || 'Learning resource'} onChange={value => setKnowledge(item.id, entry.id, 'resourceLabel', value)} /> ↗</a>}{entry.projectUrl && <a href={entry.projectUrl} target="_blank" rel="noreferrer"><EditableText value={entry.projectLabel || 'Related project'} onChange={value => setKnowledge(item.id, entry.id, 'projectLabel', value)} /> ↗</a>}</nav></section>)}</div>}{hostMode && <div className="learning-host-row"><span>{item.hidden ? 'Hidden from visitors' : 'Visible to visitors'}</span><button onClick={() => requestEditor({ kind: 'learning', id: item.id })}>Edit category ↗</button></div>}</article></Reveal>;
  })}</div> : <p className="empty-collection"><EditableText value={copy.emptyLabel} onChange={value => setCopy('emptyLabel', value)} />{hostMode && <button className="editor-add collection-add" onClick={() => requestEditor({ kind: 'learning', id: null })}>+ Add Knowledge Category</button>}</p>}</div></section>;
}
