import Reveal from './Reveal.jsx';
import EditableText from '../editor/EditableText.jsx';
import { usePortfolio } from '../context/PortfolioContext.jsx';

export default function LearningJourney() {
  const { content, update } = usePortfolio();
  const copy = content.sections.learning;
  const setCopy = (key, value) => update(current => ({ ...current, sections: { ...current.sections, learning: { ...current.sections.learning, [key]: value } } }));
  const setItem = (id, key, value) => update(current => ({ ...current, learningJourney: current.learningJourney.map(item => item.id === id ? { ...item, [key]: value } : item) }));
  return <section className="learning-section" id="learning"><div className="section"><div className="section-label"><EditableText value={copy.label} onChange={value => setCopy('label', value)} /></div><Reveal className="projects-heading"><h2><EditableText value={copy.title} onChange={value => setCopy('title', value)} /><br /><em><EditableText value={copy.emphasis} onChange={value => setCopy('emphasis', value)} /></em></h2><p><EditableText value={copy.description} multiline onChange={value => setCopy('description', value)} /></p></Reveal>{content.learningJourney.length ? <div className="learning-list">{content.learningJourney.map(item => <article key={item.id}><div><span><EditableText value={item.status} onChange={value => setItem(item.id, 'status', value)} /></span><small><EditableText value={item.period} onChange={value => setItem(item.id, 'period', value)} /></small></div><h3><EditableText value={item.title} onChange={value => setItem(item.id, 'title', value)} /></h3><p className="project-category"><EditableText value={item.category} onChange={value => setItem(item.id, 'category', value)} /></p><p><EditableText value={item.summary} multiline onChange={value => setItem(item.id, 'summary', value)} /></p><div>{[...item.topics, ...item.technologies].map((tag, index) => <EditableText key={`${tag}-${index}`} as="i" value={tag} onChange={value => { const topicsLength = item.topics.length; const key = index < topicsLength ? 'topics' : 'technologies'; const itemIndex = index < topicsLength ? index : index - topicsLength; setItem(item.id, key, item[key].map((entry, innerIndex) => innerIndex === itemIndex ? value : entry)); }} />)}</div></article>)}</div> : <p className="empty-collection"><EditableText value={copy.emptyLabel} onChange={value => setCopy('emptyLabel', value)} /></p>}</div></section>;
}
